@build example:
    #!/usr/bin/env sh
    cd "{{example}}"
    wasm-pack build --no-typescript --out-dir "www" --target web
    cp static/* www

@run example:
    just build "{{example}}"
    simple-http-server --index --nocache -- "{{example}}/www"
