[package]
name = "monaco-sys-test"
version = "0.0.0"
edition = "2018"

[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
    "Blob",
    "HtmlElement",
    "KeyboardEvent",
    "MouseEvent",
    "Url",
    "Window",
    "Worker"
]
